services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--reload"]
